site_name: Katana User Documentation
theme:
    favicon: assets/favicon.ico
    name: material
    custom_dir: overrides
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          primary: yellow
          accent: yellow
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - navigation.footer
        - navigation.instant
        #- navigation.expand
        - navigation.top
        - announce.dismiss
        - toc.integrate
        - navigation.path
extra_css:
    - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
        alternate_style: true 
  - attr_list
  - toc:
        permalink: "¶"
  - footnotes
repo_url: https://github.com/unsw-restech/unsw-restech.github.io
repo_name: unsw-restech/katana-docs
nav:
    - 'index.md'
    - 'Getting Started':
        - 'using_katana/accessing_katana.md'
        - 'using_katana/running_jobs.md'
        - 'using_katana/monitor_jobs.md'
        - 'using_katana/tips_katana.md'
        - 'using_katana/about_katana.md'
        - 'using_katana/ondemand.md'
    - 'Storage':
        - 'storage/storage_locations.md'
        - 'storage/kdm.md'
        - 'storage/data_archive.md'
        - 'storage/onedrive.md'
    - 'Software':
        - 'software/environment_modules.md'
        - 'software/installing_software.md'
        # - 'software/script_templates.md'
        #- 'software/ansys.md'
        #- 'software/biosciences.md'
        #- 'software/comsol.md'
        #- 'software/intel_compilers_and_libraries.md'
        #- 'software/java.md'
        - 'software/jupyter-notebooks.md'
        #- 'software/matlab.md'
        #- 'software/operating_systems.md'
        #- 'software/perl.md'
        - 'software/python.md'
        - 'software/r.md'
        #- 'software/sas.md'
        #- 'software/stata.md'
        #- 'software/tmux.md'
        #- 'software/zip.md'
        - 'software/others.md'
    - 'Machine Learning and AI':
        - 'AI_in_Katana/StableDiffusion.md'
    - 'Imaging':
        - 'imaging/neurodesk.md'
    #- 'Help and Support':
    - 'help_support/user_support.md'
    #- 'help_support/reference_data.md'
    - 'help_support/faq.md'
    - 'help_support/glossary.md'

plugins:
    - search
    - glightbox
    - markdownextradata: {}

extra:
    base_url: "https://localhost"
    generator: false
    analytics:
        provider: google
        property: G-W3KS3D0120

copyright: "UNSW Sydney NSW 2052 Australia | Tel: +61 2 93851000 | CRICOS: 00098G | TEQSA: PRV12055 | ABN: 57 195 873 179"

    
